[project]
name = "coding-assistant-tips"
version = "0.1.0"
description = "Evidis first Fabric MCP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-identity>=1.20.0",
    "deltalake>=0.25.4",
    "mcp[cli]>=1.3.0",
    "requests>=2.32.3",
]
